2025-03-26 13:49:39,743 - ERROR - 'PYT2'
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\test.py", line 818, in main_thread
    set_interval(sleep)
    ~~~~~~~~~~~~^^^^^^^
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\test.py", line 160, in set_interval
    tg_site_chatid = confdata['TG_CHAT_ID'][site]
                     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'PYT2'
2025-03-26 13:52:10,913 - ERROR - 'PYT2'
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\test.py", line 822, in main_thread
    set_interval(sleep)
    ~~~~~~~~~~~~^^^^^^^
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\test.py", line 160, in set_interval
    tg_site_chatid = confdata['TG_CHAT_ID'][site]
                     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'PYT2'
2025-03-26 13:53:15,400 - ERROR - 'PYT2'
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\test.py", line 822, in main_thread
    set_interval(sleep)
    ~~~~~~~~~~~~^^^^^^^
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\test.py", line 160, in set_interval
    tg_site_chatid = confdata['TG_CHAT_ID'][site]
                     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'PYT2'
2025-03-26 22:02:55,707 - ERROR - name 'alreadySent' is not defined
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 593, in main
    check_job_result = checkJobsRecieve(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 759, in checkJobsRecieve
    if alreadySent.get(current_site.upper()) is None:
       ^^^^^^^^^^^
NameError: name 'alreadySent' is not defined
2025-03-26 22:06:04,504 - ERROR - name 'alreadySent' is not defined
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 593, in main
    check_job_result = checkJobsRecieve(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 760, in checkJobsRecieve
    if alreadySent.get(current_site.upper()) is None:
       ^^^^^^^^^^^
NameError: name 'alreadySent' is not defined
2025-03-28 07:53:22,713 - ERROR - cannot access local variable 'building' where it is not associated with a value
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 668, in main
    check_job_result = checkJobsRecieve(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 874, in checkJobsRecieve
    jobno, date, dept, detail, building, img, urgent, sender, coop, ename, ncode, room, position, site))
                               ^^^^^^^^
UnboundLocalError: cannot access local variable 'building' where it is not associated with a value
2025-03-28 07:53:23,572 - ERROR - cannot access local variable 'building' where it is not associated with a value
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 949, in main_thread
    set_interval(sleep)
    ~~~~~~~~~~~~^^^^^^^
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 161, in set_interval
    site_result = main(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 683, in main
    raise e
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 668, in main
    check_job_result = checkJobsRecieve(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 874, in checkJobsRecieve
    jobno, date, dept, detail, building, img, urgent, sender, coop, ename, ncode, room, position, site))
                               ^^^^^^^^
UnboundLocalError: cannot access local variable 'building' where it is not associated with a value
2025-03-28 07:55:52,341 - ERROR - list indices must be integers or slices, not str
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 668, in main
    check_job_result = checkJobsRecieve(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 847, in checkJobsRecieve
    if not workorder in alreadySent[current_site.upper()]:
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
2025-03-28 07:55:53,936 - ERROR - list indices must be integers or slices, not str
Traceback (most recent call last):
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 951, in main_thread
    set_interval(sleep)
    ~~~~~~~~~~~~^^^^^^^
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 161, in set_interval
    site_result = main(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 683, in main
    raise e
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 668, in main
    check_job_result = checkJobsRecieve(site_data)
  File "e:\\u0e2b\u0e21\u0e32\u0e01\u0e23\u0e38\u0e01\New folder\testTG.py", line 847, in checkJobsRecieve
    if not workorder in alreadySent[current_site.upper()]:
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
